name: Update Jira Versions in Workflow

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  actions: write

jobs:
  update-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # ✅ Install `yq` before using it
      - name: Install yq
        run: |
          sudo apt update && sudo apt install -y jq
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      # ✅ Update `release.yml` directly using yq
      - name: Update Release Workflow File
        run: |
          yq eval '.on.workflow_dispatch.inputs.jira_version.options = ["1.0.0", "1.1.0", "1.2.0", "2.0.0", "major", "minor", "patch"]' -i .github/workflows/release.yml
          cat .github/workflows/release.yml  # Debug: Show updated file

      # ✅ Debug GitHub Token Scopes (Optional)
      - name: Debug GitHub Actions Token
        run: |
          echo "Checking GitHub Token Scopes..."
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user

      # ✅ Switch to release branch and pull latest changes
      - name: Switch to release branch
        run: |
          git fetch origin --prune
          git checkout dev-branch  # Replace with your actual branch name
          git pull origin dev-branch --rebase  # Ensure it's up to date

      - name: Commit Changes (If Any)
        run: |
          git add .github/workflows/release.yml
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Updated release.yml"
          fi
          git pull origin dev-branch --rebase


      # ✅ Push changes safely
      - name: Push changes
        run: |
          git push origin dev-branch
