name: Update Jira Versions in Workflow

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  actions: write
  pull-requests: write


jobs:
  update-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # ✅ Install `yq` before using it
      - name: Install yq
        run: |
          sudo apt update && sudo apt install -y jq
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      # ✅ Update `release.yml` directly using yq
      - name: Update Release Workflow File
        run: |
          yq eval '.on.workflow_dispatch.inputs.jira_version.options = ["1.0.0", "1.1.0", "1.2.0", "2.0.0", "major", "minor", "patch"]' -i .github/workflows/release.yml
          cat .github/workflows/release.yml  # Debug: Show updated file

      # ✅ Debug GitHub Token Scopes (Optional)
      - name: Debug GitHub Actions Token
        run: |
          echo "Checking GitHub Token Scopes..."
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user

      - name: Set Up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/latha-414/jenkins-project.git

      - name: Push Changes
        run: |
          git add .github/workflows/release.yml
          git commit -m "Updated Jira versions in release.yml" || echo "No changes to commit"
          git pull --rebase origin main  # Avoid conflicts
          git push origin main --force
