name: Tag and release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Select the type of release"
        required: true
        default: "patch"
        type: choice
        options:
        - major
        - minor
        - patch

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Tag and Release
        id: tag_release
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.release_type }}
          tag_prefix: v
          append_to_pre_release_tag: ''
          
      - name: Get New Tag
        run: echo "NEW_TAG=${{ steps.tag_release.outputs.new_tag }}" >> $GITHUB_ENV

      - name: Generate Changelog
        id: changelog
        uses: janheinrichmerker/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          stripHeaders: true   # Remove default changelog headers
          stripGeneratorNotice: true  # Remove generator notice
          simpleList: true  # Use a simplified list format
          output: 'CHANGELOG.md'  # Specify output file
          #prLabel: "Merged PR Details" 

     

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ env.NEW_TAG }}"
          release_name: "${{ env.NEW_TAG }}"
          body: "${{ steps.changelog.outputs.changelog }}"  # Ensure changelog is passed correctly
          draft: false
          prerelease: false
